package:
 name: rdkit-descriptastorus
 version: {{ environ.get('GIT_DESCRIBE_TAG', 'LOCAL') }}.{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}


source:
 path: .

requirements:
 build:
  - python {{ python }}
  - nose
  - six
  - rdkit
  - kyotocabinet
  - pykyotocabinet
 run:
  - python
  - rdkit
  - six
  - kyotocabinet
  - pykyotocabinet
